Add deeplink above code block that links to the API reference for each request in the console
qdrant/qdrant-web-ui pull request #142
Opened 2023-12-30 22:52 UTC by Snehil-Shah

Feature #135 

Added a "DOCS" button next to the "RUN | BEAUTIFY" buttons that directly links to that **Specific** Request's API reference.

## Features

- **Quick insert commands and access the docs**:
![insert](https://github.com/qdrant/qdrant-web-ui/assets/130062020/0766cc1f-7144-42bf-adee-afd9014bf717)

- **Dynamic Nature**: Only visible for valid commands, also works for endpoints with path variables
![dynamic](https://github.com/qdrant/qdrant-web-ui/assets/130062020/513536d9-ac45-499a-b811-3244309da12f)

2024-01-15 19:06 UTC, kartik-gupta-ij reviewed
Hey,
I think it would be better if you shift the logic to [autocomplete-openapi](https://github.com/qdrant/autocomplete-openapi)

Ideas :
1. That will return auto-completes and link.
-------------------or--------------------
2. That will return auto-completes and auto write the required json.

2024-01-15 19:11 UTC, Snehil-Shah commented
Hey, are you talking about autocompleting the request body?

2024-01-15 19:16 UTC, kartik-gupta-ij commented
Yes, only those fields which are mandatory.

2024-01-19 10:04 UTC, Snehil-Shah commented
@kartik-gupta-ij can I contact you on Discord regarding this? I have some ideas and doubts regarding this.

2024-01-19 13:15 UTC, kartik-gupta-ij commented
> @kartik-gupta-ij can I contact you on Discord? I have some ideas and doubts regarding this.

yeah sure!

2024-01-19 15:29 UTC, Snehil-Shah commented
> > @kartik-gupta-ij can I contact you on Discord? I have some ideas and doubts regarding this.
> 
> yeah sure!

DM'd you!

2024-01-20 12:48 UTC, Snehil-Shah commented
Depends on https://github.com/qdrant/autocomplete-openapi/pull/3

2024-03-16 17:21 UTC, Snehil-Shah commented
@kartik-gupta-ij `import.meta.env` is giving error when running in tests. how can I fix this?

2024-03-26 12:38 UTC, kartik-gupta-ij requested changes

2024-03-26 12:38 UTC, kartik-gupta-ij commented on src/components/EditorCommon/config/Rules.js
> +const openapi = await response.json();
```suggestion
import { OpenapiDocs } from 'autocomplete-openapi/src/request-docs';
import { readFile } from 'fs/promises';

const Method = ['POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'HEAD'];

let openapi;
if (import.meta.env.MODE === 'test') {
  const response = await readFile('public/openapi.json', 'utf8');
  openapi = JSON.parse(response);
} else {
  const response = await fetch(import.meta.env.BASE_URL + 'openapi.json');
  openapi = await response.json();
}
```
@Snehil-Shah, When running tests, vitest does not serve local files, resulting in the error you encountered.

2024-04-19 11:27 UTC, kartik-gupta-ij approved these changes

2024-04-20 14:20 UTC, merged